name: Devops Toolbox CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # https://github.com/actions/checkout
        with:
          repository: ${{ github.repository }}
          ref: 'master'
          token: ${{ github.token }}
          clean: 'true'
          fetch-depth: '1'
      - name: Fetch_all_tag
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Last Tag
        run: | 
          LAST_TAG_ENV=$(git describe --tags `git rev-list --tags --max-count=1`)
          IMAGE_NAME_ENV=$(basename $(pwd))
          echo $LAST_TAG_ENV"
          echo $IMAGE_NAME_ENV"
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Show
        run: |
          echo "LAST_TAG is $LAST_TAG_ENV"
          echo "IMAGE_NAME is IMAGE_NAME_ENV"
      - name: Build
        run: docker image build --force-rm --pull -t $IMAGE_NAME_ENV . 
      - name: Tags
        run: |
          docker tag $IMAGE_NAME_ENV ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME_ENV:$LAST_TAG_ENV
          docker tag $IMAGE_NAME_ENV ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME_ENV:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME_ENV:$LAST_TAG_ENV
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME_ENV:latest
