name: Devops Toolbox CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker image build --force-rm --pull -t docker-devops-toolbox:latest .
      - name: Last Tag
	run: echo ::set-env name=LAST_TAG::$(git describe --abbrev=0 --tags)
      - name: Tags
        run: |
          docker tag docker-devops-toolbox ${{ secrets.DOCKER_USER }}/docker-devops-toolbox:${{env.LAST_TAG}}
          docker tag docker-devops-toolbox ${{ secrets.DOCKER_USER }}/docker-devops-toolbox:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/docker-devops-toolbox:${{env.LAST_TAG}}
          docker push ${{ secrets.DOCKER_USER }}/docker-devops-toolbox:latest
